Development
codescalersinternships/iniparser-Diaa pull request #2
Opened 2023-07-09 19:02 UTC by diaabadr

2023-07-09 19:52 UTC, xmonader commented on iniparser.go
> +func NewINI() Ini {
This is wrong, It should be NewINIParser that returns Parser struct

2023-07-12 09:39 UTC, rawdaGastan requested changes
Great work. thank you!

I added some comments/improvements. kindly check them

2023-07-12 09:39 UTC, rawdaGastan commented on README.md
> +parser := iniparser.NewParser()
make sure to add how to import the package `in case someone is copying the code`

2023-07-12 09:39 UTC, rawdaGastan commented on README.md
> +# INI Parser for Go
That's great. 

we need to add `how to test (test section)`

2023-07-12 09:39 UTC, rawdaGastan commented on README.md
> +To parse INI data, create a new Parser object using the NewParser() function:
adding an INI example would be great,
for example:

```json
[owner]
name = John
organization = threefold

[database]
version = 12.6
server = 192.0.2.62
port = 143
password = 123456
protected = true
```

2023-07-12 09:39 UTC, rawdaGastan commented on .github/workflows/go-test.yaml
> +  test:
It's ok. but I think it would be better to merge test and lint jobs to prevent repeated steps (less time)

we can also add staticcheck `dominikh/staticcheck-action` and gofmt `Jerome1337/gofmt-action`

`golangci-lint` is also good

2023-07-12 09:39 UTC, rawdaGastan commented on INI-files/config.ini
> +[new[section]]
I think It would be better if this can be a great example in the readme and we can remove this directory.

2023-07-12 09:39 UTC, rawdaGastan commented on go.mod
> +require github.com/pkg/errors v0.9.1
files should have an empty line as its last line.

2023-07-12 09:39 UTC, rawdaGastan commented on iniparser.go
> +	ErrInvalidFormat    = errors.New("invalid format ")
make sure to add a comment before each exported value.

2023-07-12 09:39 UTC, rawdaGastan commented on iniparser.go
> +			return fmt.Errorf("%w invalid format at line %d", ErrInvalidFormat, idx)
I think `invalid format` will be repeated because `ErrInvalidFormat` is already mentioning it.

2023-07-12 09:39 UTC, rawdaGastan commented on iniparser.go
> +				return fmt.Errorf("%w invalid section at line %d", ErrInvalidFormat, idx)
It would be better if it's `%w: ....`

2023-07-12 09:39 UTC, rawdaGastan commented on iniparser.go
> +				return fmt.Errorf("%w invalid key at line %d", ErrInvalidFormat, idx)
It would be better if it's `%w: ....`

2023-07-12 09:39 UTC, rawdaGastan commented on iniparser.go
> +	sections := make([]string, 0, len(p.sections))
FYI: `var sections []string`, `sections := []string{}` are also good

2023-07-12 09:39 UTC, rawdaGastan commented on iniparser.go
> +
why not checking `ini` extension?

2023-07-12 09:39 UTC, rawdaGastan commented on iniparser_test.go
> +var iniInvalidFormats = []string{
we can add a test for an empty section name `[]`

2023-07-12 09:39 UTC, rawdaGastan commented on iniparser_test.go
> +}
add an empty last line :D

hint: format extensions (for go, md files, json, yml) in vscode will help you

2023-07-12 09:39 UTC, rawdaGastan commented on iniparser_test.go
> +		if !errors.Is(err, nil) {
FYI: try `github.com/stretchr/testify/assert` in your upcoming tests. It will make checks easier.

an example: we can replace those line with just `assert.NoError(t, err)` only
`assert.Equals(t, w1, w2)`
`assert.Contains(t, w, sub)`
.....

2023-07-12 09:39 UTC, rawdaGastan commented on iniparser_test.go
> +		defer os.Remove(file.Name())
we can use `tempDir`. It will remove the whole dir in the end of the test by itself

2023-07-12 09:39 UTC, rawdaGastan commented on iniparser_test.go
> +func TestSaveToFile(t *testing.T) {
don't forget to add a test for the extension when you add it :)

2023-07-12 10:10 UTC, rawdaGastan commented on go.mod
> +module iniparser
It's better to name the module as `github.com/codescalersinternships/iniparser-Diaa`
so it will be related to the repo for importing purposes

2023-07-12 10:32 UTC, rawdaGastan commented on iniparser.go
> +		if len(line) == 0 || string(line[0]) == ";" {
comments can start with a `#`

2023-07-12 11:10 UTC, rawdaGastan commented on iniparser.go
> +	var currentSection string = ""
make sure your data map is empty before you start loading

2023-07-12 14:34 UTC, rawdaGastan approved these changes

2023-07-12 14:34 UTC, merged